affordability_keywords = [
    "affordable",
    "cost",
    "quality",
    "housing",
    "rent",
    "income",
    "subsidies",
    "low-income",
    "budget",
    "financing",
    "public housing",
    "rent control",
    "economic",
    "cost-effective",
    "fiscal policy",
    "tax incentives",
    "grants",
    "funding",
    "accessibility",
    "economic development",
    "livability",
    "mortgage",
    "value",
    "price",
    "expenditure",
    "equity",
    "poverty alleviation",
    "public transport",
]

safety_keywords = [
    "walkability",
    "population growth",
    "safe",
    "secure",
    "security",
    "emergency",
    "crime prevention",
    "public safety",
    "surveillance",
    "neighborhood watch",
    "police",
    "disaster response",
    "first responders",
    "evacuation plans",
    "hazard mitigation",
    "risk assessment",
    "public health",
    "traffic safety",
    "road design",
    "speed limit",
    "pedestrian crossings",
    "light",
    "crosswalks",
    "oversee",
    "community policing",
    "CCTV",
    "alarm",
    "emergency",
    "alerts",
    "rescue",
    "fire station",
    "preparedness",
    "control",
    "earthquake-resistant structures",
    "building code",
    "regulation",
    "sanitation",
    "emergency shelters",
    "recovery planning",
    "management",
    "resilience",
    "cybersecurity",
    "protection",
    "privacy",
    "ambulance",
    "hospital capacity",
    "healthcare",
    "accessibility",
    "school safety",
    "friendly",
]

equity_keywords = [
    "education",
    "health",
    "equal access",
    "social justice",
    "inclusive",
    "diversity",
    "opportunities",
    "community health",
    "public school",
    "racial equity",
    "gender equality",
    "disability access",
    "mental health services",
    "healthcare facilities",
    "early childhood education",
    "cultural competence",
    "language services",
    "health education",
    "environmental justice",
    "food access",
    "green spaces",
    "public transportation",
    "affordable housing",
    "economic mobility",
    "job training",
    "living wage",
    "minority",
    "community engagement",
    "non-discrimination",
    "service",
    "care",
    "supportive housing",
    "substance abuse treatment",
    "rehabilitation",
    "homeless services",
    "homeless shelter",
    "refugee assistance",
    "LGBTQ",
    "participation",
    "neighborhood",
    "social cohesion",
    "conflict resolution",
    "peacebuilding",
    "human rights",
    "legal aid",
    "victim support services",
    "fair",
]

financial_keywords = [
    "investment",
    "value",
    "return",
    "workforce",
    "job",
    "development",
    "economic growth",
    "funding",
    "financing",
    "budgeting",
    "capital",
    "revenue",
    "cost-benefit analysis",
    "public-private partnerships",
    "grants",
    "loans",
    "subsidies",
    "tax incentives",
    "fiscal policy",
    "economic development",
    "infrastructure funding",
    "urban renewal",
    "real estate",
    "property value",
    "market trends",
    "commercial development",
    "business expansion",
    "entrepreneurship",
    "startups",
    "workforce training",
    "employment opportunities",
    "skill development",
    "labor market",
    "job creation programs",
    "wage levels",
    "economic diversification",
    "industry clusters",
    "trade",
    "investment strategies",
    "risk management",
    "asset management",
    "financial planning",
    "public expenditures",
    "cost control",
    "financial sustainability",
    "economic resilience",
    "business incentives",
    "local economy",
    "regional development",
    "global competitiveness",
    "foreign investment",
    "economic impact analysis",
    "sectoral analysis",
    "innovation funding",
    "technology development",
    "research and development",
    "knowledge economy",
    "talent attraction",
    "human capital",
    "workforce demographics",
    "unemployment rate",
    "labor force participation",
    "job training",
    "workplace diversity",
    "inclusive hiring",
    "living wage policies",
    "worker rights",
    "labor unions",
    "collective bargaining",
    "economic indicators",
    "financial literacy",
    "credit access",
    "microfinance",
    "small business loans",
    "venture capital",
    "angel investing",
    "economic revitalization",
    "blighted areas redevelopment",
    "gentrification",
    "affordable commercial space",
    "business districts",
    "retail development",
    "mixed-use development",
]
community_keywords = [
    "community",
    "community center",
    "community engagement",
    "community development",
    "neighborhood",
    "engagement",
    "public participation",
    "inclusive",
    "diversity",
    "arts",
    "recreation",
    "education",
    "cohesion",
    "social fabric",
    "community development",
    "civic engagement",
    "public forums",
    "stakeholder meetings",
    "volunteerism",
    "community organizing",
    "social integration",
    "multiculturalism",
    "cultural festivals",
    "public art",
    "performance spaces",
    "museums",
    "libraries",
    "community centers",
    "parks",
    "playgrounds",
    "sports facilities",
    "educational programs",
    "adult education",
    "youth outreach",
    "community gardens",
    "neighborhood associations",
    "resident input",
    "public space design",
    "accessible facilities",
    "equity",
    "intergenerational programs",
    "senior activities",
    "child-friendly spaces",
    "cultural heritage preservation",
    "historic districts",
    "local traditions",
    "community workshops",
    "skill-sharing",
    "social services",
    "health promotion",
    "wellness programs",
    "community health",
    "mental health support",
    "support groups",
    "local markets",
    "artisan crafts",
    "local businesses",
    "community events",
    "street fairs",
    "parades",
    "concerts",
    "local tourism",
    "neighborhood beautification",
    "urban greenery",
    "environmental stewardship",
    "sustainability initiatives",
    "neighborhood safety",
    "crime prevention",
    "community policing",
    "dispute resolution",
    "mediation services",
    "community advocacy",
    "political representation",
    "grassroots movements",
    "social justice initiatives",
    "equality campaigns",
    "digital inclusion",
    "online communities",
    "social media engagement",
    "public access to information",
    "community broadcasting",
    "local news",
    "citizen journalism",
    "collaborative planning",
    "feedback mechanisms",
    "resident surveys",
    "participatory budgeting",
    "local governance",
    "community leadership",
    "youth leadership",
    "elder wisdom",
    "volunteering opportunities",
    "nonprofit organizations",
    "faith-based initiatives",
    "interfaith dialogue",
    "community resilience",
    "emergency preparedness",
    "disaster recovery",
    "community support networks",
]

commercial_keywords = [
    "tourism",
    "commercial",
    "retail",
    "mixed-use",
    "business district",
    "shopping centers",
    "marketplaces",
    "high streets",
    "storefronts",
    "consumer behavior",
    "foot traffic",
    "retail therapy",
    "branding",
    "franchises",
    "local businesses",
    "entrepreneurship",
    "startups",
    "commercial real estate",
    "leasing",
    "property development",
    "economic development",
    "business hubs",
    "office spaces",
    "work-live-play environments",
    "urban regeneration",
    "gentrification",
    "destination marketing",
    "tourist attractions",
    "heritage tourism",
    "eco-tourism",
    "cultural tourism",
    "adventure tourism",
    "medical tourism",
    "hospitality industry",
    "hotels",
    "resorts",
    "travel services",
    "visitor experience",
    "tour guides",
    "local cuisine",
    "food markets",
    "nightlife",
    "entertainment venues",
    "arts and culture",
    "event hosting",
    "conventions",
    "trade fairs",
    "expos",
    "shopping festivals",
    "seasonal sales",
    "discount offers",
    "customer service",
    "e-commerce",
    "online retail",
    "digital transformation",
    "supply chain",
    "logistics",
    "inventory management",
    "product diversification",
    "market trends",
    "consumer demographics",
    "shopping behavior analysis",
    "retail technology",
    "point of sale systems",
    "customer loyalty programs",
    "brand partnerships",
    "sponsorships",
    "advertising",
    "marketing campaigns",
    "social media promotion",
    "influencer marketing",
    "urban aesthetics",
    "store design",
    "visual merchandising",
    "retail innovation",
    "shopping experiences",
    "retailtainment",
    "pedestrian zones",
    "public spaces",
    "street furniture",
    "urban landscaping",
    "outdoor advertising",
    "signage",
    "commercial zoning",
    "land use planning",
    "regulatory compliance",
    "business licensing",
    "tax incentives",
    "economic incentives",
    "infrastructure support",
    "public-private partnerships",
    "community impact",
    "sustainable practices",
    "corporate social responsibility",
]

print("affordability_keywords:", len(affordability_keywords))
print("safety_keywords", len(safety_keywords))
print("equity_keywords", len(equity_keywords))
print("community_keywords", len(community_keywords))
print("financial_keywords",len(financial_keywords))